var test01 = {
    "Results": [
        {
            "VesselID": 306287,
            "CompanyID": 123,
            "MLSID": 307279,
            "VesselStatus": 1,
            "VesselCondition": 2,
            "Year": 2014,
            "MainPhotoID": 3527902,
            "VesselType": 2,
            "ModelYear": 2014,
            "YearBuilt": 2014,
            "MainCategoryID": 2382,
            "MainCategoryText": "Motor Yacht",
            "SubCategoryID": 3194,
            "SubCategoryText": "Flybridge",
            "StateRooms": 4,
            "Sleeps": 10,
            "LOAFeet": 76.000000,
            "Length": 76.0000,
            "Beam": 18.5000,
            "MinDraft": 5.2500,
            "MaxDraft": 5.5833,
            "MSRPPrice": 0.0000,
            "MSRPPriceCurrencyID": 2563,
            "Buildername": "MONTE CARLO YACHTS",
            "BuilderID": 3868,
            "WeightUnitType": 1,
            "LOAMeters": 23.160000,
            "BeamFeet": 18.500000,
            "BeamMeters": 5.630000,
            "DraftMinFeet": 5.250000,
            "DraftMinMeters": 1.600000,
            "DraftMaxFeet": 5.580000,
            "DraftMaxMeters": 1.700000,
            "GrossTonnage": 0.0,
            "GrossTonnagePounds": 0.0,
            "GrossTonnageConverted": 0.0,
            "LengthUnit": 1,
            "WeightUnit": 1,
            "VolumeUnit": 1,
            "tags": [],
            "AskingPrice": 2499999.0000,
            "AskingPriceCurrency": 2563,
            "PriceOnApplication": false,
            "IsStartingPrice": false,
            "VesselName": "MANILA",
            "AskingPriceFormatted": "$2,499,999 USD",
            "AskingPriceFormattedNoCurrency": "$2,499,999",
            "AskingPriceCompare": 2499999.000000,
            "MSRPPriceFormatted": "Price on Application",
            "MSRPPriceFormattedNoCurrency": "Price on Application",
            "BuilderName": "MONTE CARLO YACHTS",
            "BrokerTeaser": "2014 Monte Carlo Yachts MCY 76",
            "Country": "United States",
            "State": "California",
            "City": "Los Angeles",
            "RegionID": 456,
            "Region": "California - South",
            "Cruising": false,
            "LocationCountryID": 233,
            "LocationCountry": "United States",
            "LocationStateID": 1416,
            "HullMaterial": "Fiberglass",
            "HullMaterialID": 2434,
            "HasVideo": false,
            "LocationState": "California",
            "LocationCityID": 120784,
            "LocationCity": "Los Angeles",
            "LocationSubRegionID": 12,
            "LocationSubRegion": "North America",
            "MainPhotoUrl": "https://s3.amazonaws.com/boss.yatco.com/ForSale/Vessel/Photo/306287/small_3527902.jpg",
            "MainPhotoMedURL": "https://s3.amazonaws.com/boss.yatco.com/ForSale/Vessel/Photo/306287/medium_3527902.jpg",
            "Model": "MCY 76",
            "IsModel": false,
            "SoldDate": "2022-05-23T20:00:00",
            "SoldSecret": false,
            "ActiveDate": "2022-05-25T09:56:01.813",
            "ModifiedDate": "2022-05-25T09:56:01.837",
            "DaysOnMarket": 701,
            "DaysTillExpiration": "N/A",
            "RecordAgeHours": 16812,
            "BrokerList": [
                {
                    "CompanyID": 123,
                    "OfficeID": 123,
                    "BrokerID": 25969,
                    "BrokerName": "Peter Schmidt",
                    "BrokerPhone": "772-266-7102",
                    "BrokerEmail": "peter@unitedyacht.com",
                    "BrokerPhotoUrlSmall": "https://s3-external-1.amazonaws.com/common.yatcoboss.com/PhotoDefault/Account/default.jpg",
                    "CompanyName": "United Yacht Sales, LLC",
                    "CompanyAddress1": "110 SW Atlanta Avenue",
                    "CompanyAddress2": "",
                    "CompanyCity": "Stuart",
                    "CompanyState": "Florida",
                    "CompanyZip": "34994",
                    "CompanyCountry": "United States",
                    "CompanyPhotoUrl": "https://s3-external-1.amazonaws.com/boss.yatco.com/CMS/Company/Photo/small_2016.png",
                    "VesselID": 306287
                }
            ],
            "AssistantList": [],
            "DataSource": 1,
            "Open": false,
            "AgreementTypeID": 2546,
            "SearchedLengthUnit": 1,
            "SearchedCurrency": 0,
            "SearchedVolumeUnit": 0,
            "LoaFormat": "76'",
            "MaxDraftFormat": "5' 7\"",
            "MinDraftFormat": "5' 3\"",
            "BeamFormat": "18' 6\"",
            "AcceptsCrypto": false,
            "ShowOnCustomerSite": true
        },
        {
            "VesselID": 233418,
            "CompanyID": 136,
            "MLSID": 233418,
            "VesselStatus": 1,
            "VesselCondition": 2,
            "Year": 2012,
            "MainPhotoID": 1560546,
            "VesselType": 2,
            "ModelYear": 2012,
            "YearBuilt": 2012,
            "MainCategoryID": 3510,
            "MainCategoryText": "Boats",
            "SubCategoryID": 3161,
            "SubCategoryText": "Center Console",
            "StateRooms": 1,
            "TaxPaidID": 2564,
            "LOAFeet": 37.000000,
            "Length": 37.0000,
            "Beam": 11.5000,
            "MinDraft": 2.0000,
            "MaxDraft": 0.0,
            "MSRPPrice": 0.0000,
            "MSRPPriceCurrencyID": 2563,
            "Buildername": "BOSTON WHALER",
            "BuilderID": 307,
            "WeightUnitType": 1,
            "LOAMeters": 11.270000,
            "BeamFeet": 11.500000,
            "BeamMeters": 3.500000,
            "DraftMinFeet": 2.000000,
            "DraftMinMeters": 0.600000,
            "DraftMaxFeet": 0.000000,
            "DraftMaxMeters": 0.000000,
            "GrossTonnage": 0.0,
            "GrossTonnagePounds": 0.0,
            "GrossTonnageConverted": 0.0,
            "LengthUnit": 1,
            "WeightUnit": 1,
            "VolumeUnit": 1,
            "tags": [],
            "AskingPrice": 325000.0000,
            "AskingPriceCurrency": 2563,
            "PriceOnApplication": false,
            "IsStartingPrice": false,
            "VesselName": "37FT 2012 BOSTON WHALER 370 OUTRAGE",
            "PreviousName1": "",
            "PreviousName2": "",
            "PreviousName3": "",
            "PreviousName4": "",
            "PreviousName5": "",
            "AskingPriceFormatted": "$325,000 USD",
            "AskingPriceFormattedNoCurrency": "$325,000",
            "AskingPriceCompare": 325000.000000,
            "MSRPPriceFormatted": "Price on Application",
            "MSRPPriceFormattedNoCurrency": "Price on Application",
            "BuilderName": "BOSTON WHALER",
            "BrokerTeaser": "",
            "Country": "United States",
            "State": "California",
            "City": "Newport Beach",
            "RegionID": 456,
            "Region": "California - South",
            "Cruising": false,
            "LocationCountryID": 233,
            "LocationCountry": "United States",
            "LocationStateID": 1416,
            "HullMaterial": "Fiberglass",
            "HullMaterialID": 2434,
            "HasVideo": false,
            "LocationState": "California",
            "LocationCityID": 122853,
            "LocationCity": "Newport Beach",
            "LocationSubRegionID": 12,
            "LocationSubRegion": "North America",
            "MainPhotoUrl": "https://s3.amazonaws.com/boss.yatco.com/ForSale/Vessel/Photo/233418/small_1560546.jpg",
            "MainPhotoMedURL": "https://s3.amazonaws.com/boss.yatco.com/ForSale/Vessel/Photo/233418/medium_1560546.jpg",
            "Model": "370 Outrage",
            "IsModel": false,
            "SoldDate": "2023-01-03T19:00:00",
            "SoldSecret": false,
            "ActiveDate": "2023-01-05T02:48:16.177",
            "ModifiedDate": "2023-01-05T02:48:23.407",
            "DaysOnMarket": 476,
            "DaysTillExpiration": "N/A",
            "RecordAgeHours": 11418,
            "BrokerList": [
                {
                    "CompanyID": 136,
                    "OfficeID": 812,
                    "BrokerID": 3250,
                    "BrokerName": "Denison California",
                    "BrokerPhone": "954.763.3971",
                    "BrokerEmail": "CaliforniaLeads@denisonyachting.com",
                    "BrokerPhotoUrlSmall": "https://s3-external-1.amazonaws.com/boss.yatco.com/CMS/Account/Photo/small_1833.jpg",
                    "CompanyName": "Denison Yachting - California ",
                    "CompanyAddress1": "2429 West Coast Highway",
                    "CompanyAddress2": "#101",
                    "CompanyCity": "Newport Beach ",
                    "CompanyState": "California",
                    "CompanyZip": "92663",
                    "CompanyCountry": "United States",
                    "CompanyPhotoUrl": "https://s3-external-1.amazonaws.com/boss.yatco.com/CMS/Company/Photo/small_2027.jpg",
                    "VesselID": 233418
                }
            ],
            "AssistantList": [],
            "DataSource": 1,
            "Open": false,
            "AgreementTypeID": 2546,
            "SearchedLengthUnit": 1,
            "SearchedCurrency": 0,
            "SearchedVolumeUnit": 0,
            "LoaFormat": "37'",
            "MaxDraftFormat": "--",
            "MinDraftFormat": "2'",
            "BeamFormat": "11' 6\"",
            "AcceptsCrypto": false,
            "ShowOnCustomerSite": true
        },
        {
            "VesselID": 244137,
            "CompanyID": 136,
            "MLSID": 244137,
            "VesselStatus": 4,
            "VesselCondition": 2,
            "Year": 2008,
            "MainPhotoID": 1984285,
            "VesselType": 2,
            "ModelYear": 2008,
            "YearBuilt": 2008,
            "MainCategoryID": 2375,
            "MainCategoryText": "Cruising Yacht",
            "SubCategoryID": 3154,
            "SubCategoryText": "Sport Cruiser",
            "StateRooms": 0,
            "TaxPaidID": 2564,
            "LOAFeet": 35.000000,
            "Length": 35.0000,
            "Beam": 12.0000,
            "MinDraft": 0.0,
            "MaxDraft": 3.0833,
            "MSRPPrice": 0.0000,
            "MSRPPriceCurrencyID": 2563,
            "Buildername": "SEA RAY",
            "BuilderID": 2216,
            "WeightUnitType": 1,
            "LOAMeters": 10.660000,
            "BeamFeet": 12.000000,
            "BeamMeters": 3.650000,
            "DraftMinFeet": 0.000000,
            "DraftMinMeters": 0.000000,
            "DraftMaxFeet": 3.080000,
            "DraftMaxMeters": 0.930000,
            "GrossTonnage": 0.0,
            "GrossTonnagePounds": 0.0,
            "GrossTonnageConverted": 0.0,
            "LengthUnit": 1,
            "WeightUnit": 1,
            "VolumeUnit": 1,
            "tags": [],
            "AskingPrice": 139000.0000,
            "AskingPriceCurrency": 2563,
            "PriceOnApplication": false,
            "IsStartingPrice": false,
            "VesselName": "35FT 2008 SEA RAY 350 SUNDANCER",
            "PreviousName1": "",
            "PreviousName2": "",
            "PreviousName3": "",
            "PreviousName4": "",
            "PreviousName5": "",
            "AskingPriceFormatted": "$139,000 USD",
            "AskingPriceFormattedNoCurrency": "$139,000",
            "AskingPriceCompare": 139000.000000,
            "MSRPPriceFormatted": "Price on Application",
            "MSRPPriceFormattedNoCurrency": "Price on Application",
            "BuilderName": "SEA RAY",
            "BrokerTeaser": "",
            "Country": "United States",
            "State": "California",
            "City": "Marina del Rey",
            "RegionID": 456,
            "Region": "California - South",
            "Cruising": false,
            "LocationCountryID": 233,
            "LocationCountry": "United States",
            "LocationStateID": 1416,
            "HullMaterial": "Fiberglass",
            "HullMaterialID": 2434,
            "HasVideo": false,
            "LocationState": "California",
            "LocationCityID": 121224,
            "LocationCity": "Marina del Rey",
            "LocationSubRegionID": 12,
            "LocationSubRegion": "North America",
            "MainPhotoUrl": "https://s3.amazonaws.com/boss.yatco.com/ForSale/Vessel/Photo/244137/small_1984285.jpg",
            "MainPhotoMedURL": "https://s3.amazonaws.com/boss.yatco.com/ForSale/Vessel/Photo/244137/medium_1984285.jpg",
            "Model": " Condition  New    Used Length*    37.5  ft Year*  2008",
            "IsModel": false,
            "SoldSecret": false,
            "ActiveDate": "2018-01-25T16:00:30.547",
            "ModifiedDate": "2018-01-25T16:00:31",
            "DaysOnMarket": 2282,
            "DaysTillExpiration": "N/A",
            "RecordAgeHours": 54748,
            "BrokerList": [
                {
                    "CompanyID": 136,
                    "OfficeID": 812,
                    "BrokerID": 3250,
                    "BrokerName": "Denison California",
                    "BrokerPhone": "954.763.3971",
                    "BrokerEmail": "CaliforniaLeads@denisonyachting.com",
                    "BrokerPhotoUrlSmall": "https://s3-external-1.amazonaws.com/boss.yatco.com/CMS/Account/Photo/small_1833.jpg",
                    "CompanyName": "Denison Yachting - California ",
                    "CompanyAddress1": "2429 West Coast Highway",
                    "CompanyAddress2": "#101",
                    "CompanyCity": "Newport Beach ",
                    "CompanyState": "California",
                    "CompanyZip": "92663",
                    "CompanyCountry": "United States",
                    "CompanyPhotoUrl": "https://s3-external-1.amazonaws.com/boss.yatco.com/CMS/Company/Photo/small_2027.jpg",
                    "VesselID": 244137
                }
            ],
            "AssistantList": [],
            "DataSource": 1,
            "Open": false,
            "AgreementTypeID": 2546,
            "SearchedLengthUnit": 1,
            "SearchedCurrency": 0,
            "SearchedVolumeUnit": 0,
            "LoaFormat": "35'",
            "MaxDraftFormat": "3' 1\"",
            "MinDraftFormat": "--",
            "BeamFormat": "12'",
            "AcceptsCrypto": false,
            "ShowOnCustomerSite": true
        },
        {
            "VesselID": 306643,
            "CompanyID": 841,
            "MLSID": 307973,
            "VesselStatus": 1,
            "VesselCondition": 2,
            "Year": 2007,
            "MainPhotoID": 3697964,
            "VesselType": 2,
            "ModelYear": 2007,
            "YearBuilt": 2007,
            "MainCategoryID": 2382,
            "MainCategoryText": "Motor Yacht",
            "SubCategoryID": 3194,
            "SubCategoryText": "Flybridge",
            "StateRooms": 3,
            "Sleeps": 7,
            "TaxPaidID": 2566,
            "LOAFeet": 65.000000,
            "Length": 65.0000,
            "Beam": 17.2500,
            "MinDraft": 0.0,
            "MaxDraft": 4.9166,
            "MSRPPrice": 0.0000,
            "MSRPPriceCurrencyID": 2563,
            "Buildername": "AZIMUT YACHTS",
            "BuilderID": 174,
            "WeightUnitType": 1,
            "LOAMeters": 19.810000,
            "BeamFeet": 17.250000,
            "BeamMeters": 5.250000,
            "DraftMinFeet": 0.000000,
            "DraftMinMeters": 0.000000,
            "DraftMaxFeet": 4.910000,
            "DraftMaxMeters": 1.490000,
            "GrossTonnage": 0.0,
            "GrossTonnagePounds": 0.0,
            "GrossTonnageConverted": 0.0,
            "LengthUnit": 1,
            "WeightUnit": 1,
            "VolumeUnit": 1,
            "tags": [],
            "AskingPrice": 829000.0000,
            "AskingPriceCurrency": 2563,
            "PriceOnApplication": false,
            "IsStartingPrice": false,
            "VesselName": "NAUTI TIME",
            "AskingPriceFormatted": "$829,000 USD",
            "AskingPriceFormattedNoCurrency": "$829,000",
            "AskingPriceCompare": 829000.000000,
            "MSRPPriceFormatted": "Price on Application",
            "MSRPPriceFormattedNoCurrency": "Price on Application",
            "BuilderName": "AZIMUT YACHTS",
            "BrokerTeaser": "Fresh Water Vessel with only 650 hrs & the only Azimut 62E on the West Coast",
            "Country": "United States",
            "State": "California",
            "City": "San Diego",
            "RegionID": 456,
            "Region": "California - South",
            "Cruising": false,
            "LocationCountryID": 233,
            "LocationCountry": "United States",
            "LocationStateID": 1416,
            "HullMaterial": "Fiberglass",
            "HullMaterialID": 2434,
            "HasVideo": false,
            "LocationState": "California",
            "LocationCityID": 125802,
            "LocationCity": "San Diego",
            "LocationSubRegionID": 12,
            "LocationSubRegion": "North America",
            "MainPhotoUrl": "https://s3.amazonaws.com/boss.yatco.com/ForSale/Vessel/Photo/306643/small_3697964.jpg",
            "MainPhotoMedURL": "https://s3.amazonaws.com/boss.yatco.com/ForSale/Vessel/Photo/306643/medium_3697964.jpg",
            "Model": "62E",
            "IsModel": false,
            "SoldDate": "2022-06-09T20:00:00",
            "SoldSecret": false,
            "ActiveDate": "2022-06-14T23:48:50.247",
            "ModifiedDate": "2023-04-25T12:11:32",
            "DaysOnMarket": 680,
            "DaysTillExpiration": "N/A",
            "RecordAgeHours": 8769,
            "BrokerList": [
                {
                    "CompanyID": 841,
                    "OfficeID": 841,
                    "BrokerID": 20613,
                    "BrokerName": "Kami Pahlavan",
                    "BrokerPhone": "310-838-8000",
                    "BrokerEmail": "kami@kapainternational.com",
                    "BrokerMobile": "310-801-5900",
                    "BrokerPhotoUrlSmall": "https://s3-external-1.amazonaws.com/common.yatcoboss.com/PhotoDefault/Account/default.jpg",
                    "CompanyName": "Kapa International ",
                    "CompanyAddress1": "3141 Donald Douglas Loop South",
                    "CompanyCity": "Santa Monica",
                    "CompanyState": "California",
                    "CompanyZip": "90405",
                    "CompanyCountry": "United States",
                    "CompanyPhotoUrl": "https://s3-external-1.amazonaws.com/boss.yatco.com/CMS/Company/Photo/small_506.jpg",
                    "VesselID": 306643
                }
            ],
            "AssistantList": [],
            "DataSource": 1,
            "Open": false,
            "AgreementTypeID": 2546,
            "SearchedLengthUnit": 1,
            "SearchedCurrency": 0,
            "SearchedVolumeUnit": 0,
            "LoaFormat": "65'",
            "MaxDraftFormat": "4' 11\"",
            "MinDraftFormat": "--",
            "BeamFormat": "17' 3\"",
            "AcceptsCrypto": false,
            "ShowOnCustomerSite": true
        },
        {
            "VesselID": 296425,
            "CompanyID": 1220,
            "MLSID": 268374,
            "VesselStatus": 4,
            "VesselCondition": 2,
            "Year": 2006,
            "MainPhotoID": 3098340,
            "VesselType": 1,
            "ModelYear": 2006,
            "YearBuilt": 2006,
            "MainCategoryID": 2384,
            "MainCategoryText": "Catamaran",
            "SubCategoryID": 3232,
            "SubCategoryText": "Cruiser",
            "StateRooms": 3,
            "Sleeps": 8,
            "LOAFeet": 33.500000,
            "Length": 33.5000,
            "Beam": 14.0000,
            "MinDraft": 1.5000,
            "MaxDraft": 5.5000,
            "MSRPPrice": 0.0000,
            "MSRPPriceCurrencyID": 2563,
            "Buildername": "GEMINI CATAMARANS",
            "BuilderID": 981,
            "WeightUnitType": 1,
            "LOAMeters": 10.210000,
            "BeamFeet": 14.000000,
            "BeamMeters": 4.260000,
            "DraftMinFeet": 1.500000,
            "DraftMinMeters": 0.450000,
            "DraftMaxFeet": 5.500000,
            "DraftMaxMeters": 1.670000,
            "GrossTonnage": 0.0,
            "GrossTonnagePounds": 0.0,
            "GrossTonnageConverted": 0.0,
            "LengthUnit": 1,
            "WeightUnit": 1,
            "VolumeUnit": 1,
            "tags": [],
            "AskingPrice": 114900.0000,
            "AskingPriceCurrency": 2563,
            "PriceOnApplication": false,
            "IsStartingPrice": false,
            "VesselName": "ANDIMO",
            "AskingPriceFormatted": "$114,900 USD",
            "AskingPriceFormattedNoCurrency": "$114,900",
            "AskingPriceCompare": 114900.000000,
            "MSRPPriceFormatted": "Price on Application",
            "MSRPPriceFormattedNoCurrency": "Price on Application",
            "BuilderName": "GEMINI CATAMARANS",
            "BrokerTeaser": "Used Geminis generally offer excellent value, outstanding accommodations, and solid sailing performance. Seller's bought the vessel new and have continued to keep the vessel in pristine condition. Currently dry docked for your viewing.",
            "Country": "United States",
            "State": "California",
            "City": "Napa",
            "RegionID": 455,
            "Region": "California - North",
            "LocationCountryID": 233,
            "LocationCountry": "United States",
            "LocationStateID": 1416,
            "HullMaterial": "Fiberglass",
            "HullMaterialID": 2434,
            "HasVideo": false,
            "LocationState": "California",
            "LocationCityID": 122546,
            "LocationCity": "Napa",
            "LocationSubRegionID": 12,
            "LocationSubRegion": "North America",
            "MainPhotoUrl": "https://s3.amazonaws.com/boss.yatco.com/ForSale/Vessel/Photo/296425/small_3098340.jpg",
            "MainPhotoMedURL": "https://s3.amazonaws.com/boss.yatco.com/ForSale/Vessel/Photo/296425/medium_3098340.jpg",
            "Model": "105Mc",
            "IsModel": false,
            "SoldDate": "2020-11-11T18:59:00",
            "SoldSecret": false,
            "ActiveDate": "2020-11-12T19:45:12.593",
            "ModifiedDate": "2021-03-16T14:35:33.177",
            "DaysOnMarket": 1259,
            "DaysTillExpiration": "N/A",
            "RecordAgeHours": 27247,
            "BrokerList": [
                {
                    "CompanyID": 1220,
                    "OfficeID": 1277,
                    "BrokerID": 26888,
                    "BrokerName": "Kirby Long",
                    "BrokerPhone": "(707) 252-8011",
                    "BrokerEmail": "nvmkirby@yahoo.com",
                    "BrokerMobile": "707-732-6101",
                    "BrokerPhotoUrlSmall": "https://s3-external-1.amazonaws.com/common.yatcoboss.com/PhotoDefault/Account/default.jpg",
                    "CompanyName": "Napa Valley Marina",
                    "CompanyAddress1": "1200 Milton Rd",
                    "CompanyCity": "Napa",
                    "CompanyState": "California",
                    "CompanyZip": "94559",
                    "CompanyCountry": "United States",
                    "CompanyPhotoUrl": "https://s3-external-1.amazonaws.com/boss.yatco.com/CMS/Company/Photo/small_2297.jpg",
                    "VesselID": 296425
                }
            ],
            "AssistantList": [],
            "DataSource": 1,
            "Open": false,
            "AgreementTypeID": 2546,
            "SearchedLengthUnit": 1,
            "SearchedCurrency": 0,
            "SearchedVolumeUnit": 0,
            "LoaFormat": "33' 6\"",
            "MaxDraftFormat": "5' 6\"",
            "MinDraftFormat": "1' 6\"",
            "BeamFormat": "14'",
            "AcceptsCrypto": false,
            "ShowOnCustomerSite": true
        },
        {
            "VesselID": 239442,
            "CompanyID": 899,
            "MLSID": 239442,
            "VesselStatus": 1,
            "VesselCondition": 2,
            "Year": 2003,
            "MainPhotoID": 1796087,
            "VesselType": 1,
            "ModelYear": 2003,
            "YearBuilt": 2003,
            "MainCategoryID": 2673,
            "MainCategoryText": "Racing Sailboat",
            "StateRooms": 0,
            "TaxPaidID": 2564,
            "LOAFeet": 40.000000,
            "Length": 40.0000,
            "Beam": 13.1666,
            "MinDraft": 0.0,
            "MaxDraft": 0.0,
            "MSRPPrice": 0.0000,
            "MSRPPriceCurrencyID": 2563,
            "Buildername": "CARROLL MARINE",
            "BuilderID": 449,
            "WeightUnitType": 1,
            "LOAMeters": 12.190000,
            "BeamFeet": 13.160000,
            "BeamMeters": 4.010000,
            "DraftMinFeet": 0.000000,
            "DraftMinMeters": 0.000000,
            "DraftMaxFeet": 0.000000,
            "DraftMaxMeters": 0.000000,
            "GrossTonnage": 0.0,
            "GrossTonnagePounds": 0.0,
            "GrossTonnageConverted": 0.0,
            "LengthUnit": 1,
            "WeightUnit": 1,
            "VolumeUnit": 1,
            "tags": [],
            "AskingPrice": 99500.0000,
            "AskingPriceCurrency": 2563,
            "PriceOnApplication": false,
            "IsStartingPrice": false,
            "VesselName": "CAETUS",
            "PreviousName1": "",
            "PreviousName2": "",
            "PreviousName3": "",
            "PreviousName4": "",
            "PreviousName5": "",
            "AskingPriceFormatted": "$99,500 USD",
            "AskingPriceFormattedNoCurrency": "$99,500",
            "AskingPriceCompare": 99500.000000,
            "MSRPPriceFormatted": "Price on Application",
            "MSRPPriceFormattedNoCurrency": "Price on Application",
            "BuilderName": "CARROLL MARINE",
            "BrokerTeaser": "",
            "Country": "United States",
            "State": "California",
            "City": "",
            "RegionID": 456,
            "Region": "California - South",
            "Cruising": false,
            "LocationCountryID": 233,
            "LocationCountry": "United States",
            "LocationStateID": 1416,
            "HullMaterial": "Fiberglass",
            "HullMaterialID": 2434,
            "HasVideo": false,
            "LocationState": "California",
            "LocationCityID": 0,
            "LocationCity": "",
            "LocationSubRegionID": 12,
            "LocationSubRegion": "North America",
            "MainPhotoUrl": "https://s3.amazonaws.com/boss.yatco.com/ForSale/Vessel/Photo/239442/small_1796087.jpg",
            "MainPhotoMedURL": "https://s3.amazonaws.com/boss.yatco.com/ForSale/Vessel/Photo/239442/medium_1796087.jpg",
            "Model": "Farr 40",
            "IsModel": false,
            "SoldSecret": false,
            "ActiveDate": "2017-05-24T17:41:05.537",
            "ModifiedDate": "2017-05-26T12:28:19",
            "DaysOnMarket": 2528,
            "DaysTillExpiration": "N/A",
            "RecordAgeHours": 60609,
            "BrokerList": [
                {
                    "CompanyID": 899,
                    "OfficeID": 899,
                    "BrokerID": 22734,
                    "BrokerName": "Stephen Rock",
                    "BrokerEmail": "reichelpughbrokerage@gmail.com",
                    "BrokerPhotoUrlSmall": "https://s3-external-1.amazonaws.com/common.yatcoboss.com/PhotoDefault/Account/default.jpg",
                    "CompanyName": "Reichel-Pugh Yacht Brokerage",
                    "CompanyAddress1": "2726 Shelter Island Dr #535",
                    "CompanyAddress2": "",
                    "CompanyCity": "San Diego",
                    "CompanyState": "California",
                    "CompanyZip": "92106",
                    "CompanyCountry": "United States",
                    "CompanyPhotoUrl": "https://s3-external-1.amazonaws.com/common.yatcoboss.com/PhotoDefault/Company/yatcoboss_nologo.jpg",
                    "VesselID": 239442
                }
            ],
            "AssistantList": [],
            "DataSource": 1,
            "Open": false,
            "AgreementTypeID": 2546,
            "SearchedLengthUnit": 1,
            "SearchedCurrency": 0,
            "SearchedVolumeUnit": 0,
            "LoaFormat": "40'",
            "MaxDraftFormat": "--",
            "MinDraftFormat": "--",
            "BeamFormat": "13' 2\"",
            "AcceptsCrypto": false,
            "ShowOnCustomerSite": true
        },
        {
            "VesselID": 303229,
            "CompanyID": 1087,
            "MLSID": 275198,
            "VesselStatus": 1,
            "VesselCondition": 2,
            "Year": 2001,
            "MainPhotoID": 3390584,
            "VesselType": 2,
            "ModelYear": 2001,
            "YearBuilt": 2001,
            "MainCategoryID": 2375,
            "MainCategoryText": "Cruising Yacht",
            "SubCategoryID": 3153,
            "SubCategoryText": "Sedan Cruiser",
            "StateRooms": 0,
            "LOAFeet": 26.000000,
            "Length": 26.0000,
            "Beam": 10.0000,
            "MinDraft": 0.0,
            "MaxDraft": 2.5000,
            "MSRPPrice": 0.0000,
            "MSRPPriceCurrencyID": 2563,
            "Buildername": "FORTIER",
            "BuilderID": 4859,
            "WeightUnitType": 1,
            "LOAMeters": 7.920000,
            "BeamFeet": 10.000000,
            "BeamMeters": 3.040000,
            "DraftMinFeet": 0.000000,
            "DraftMinMeters": 0.000000,
            "DraftMaxFeet": 2.500000,
            "DraftMaxMeters": 0.760000,
            "GrossTonnage": 0.0,
            "GrossTonnagePounds": 0.0,
            "GrossTonnageConverted": 0.0,
            "LengthUnit": 1,
            "WeightUnit": 1,
            "VolumeUnit": 1,
            "tags": [],
            "AskingPrice": 70000.0000,
            "AskingPriceCurrency": 2563,
            "PriceOnApplication": false,
            "IsStartingPrice": false,
            "VesselName": "LAGNAIPPE",
            "AskingPriceFormatted": "$70,000 USD",
            "AskingPriceFormattedNoCurrency": "$70,000",
            "AskingPriceCompare": 70000.000000,
            "MSRPPriceFormatted": "Price on Application",
            "MSRPPriceFormattedNoCurrency": "Price on Application",
            "BuilderName": "FORTIER",
            "BrokerTeaser": "Low hour cruiser!",
            "Country": "United States",
            "State": "California",
            "City": "Isleton",
            "RegionID": 455,
            "Region": "California - North",
            "LocationCountryID": 233,
            "LocationCountry": "United States",
            "LocationStateID": 1416,
            "HullMaterial": "Fiberglass",
            "HullMaterialID": 2434,
            "HasVideo": false,
            "LocationState": "California",
            "LocationCityID": 1150130,
            "LocationCity": "Isleton",
            "LocationSubRegionID": 12,
            "LocationSubRegion": "North America",
            "MainPhotoUrl": "https://s3.amazonaws.com/boss.yatco.com/ForSale/Vessel/Photo/303229/small_3390584.jpg",
            "MainPhotoMedURL": "https://s3.amazonaws.com/boss.yatco.com/ForSale/Vessel/Photo/303229/medium_3390584.jpg",
            "IsModel": false,
            "SoldDate": "2021-12-10T19:00:00",
            "SoldSecret": false,
            "ActiveDate": "2021-12-13T11:35:57.703",
            "ModifiedDate": "2022-02-17T00:14:17.887",
            "DaysOnMarket": 864,
            "DaysTillExpiration": "N/A",
            "RecordAgeHours": 19148,
            "BrokerList": [
                {
                    "CompanyID": 1087,
                    "OfficeID": 1106,
                    "BrokerID": 26102,
                    "BrokerName": "Nate Eckler",
                    "BrokerPhone": "1-855-547-4533",
                    "BrokerEmail": "nate@ishkeesh.com",
                    "BrokerPhotoUrlSmall": "https://s3-external-1.amazonaws.com/boss.yatco.com/CMS/Account/Photo/small_1761.jpg",
                    "CompanyName": "Ishkeesh Marine Services - Richmond",
                    "CompanyAddress1": "1338 Marina Way S",
                    "CompanyCity": "Richmond",
                    "CompanyState": "California",
                    "CompanyZip": "94804",
                    "CompanyCountry": "United States",
                    "CompanyPhotoUrl": "https://s3-external-1.amazonaws.com/boss.yatco.com/CMS/Company/Photo/small_2006.jpg",
                    "VesselID": 303229
                }
            ],
            "AssistantList": [],
            "DataSource": 1,
            "Open": false,
            "AgreementTypeID": 2546,
            "SearchedLengthUnit": 1,
            "SearchedCurrency": 0,
            "SearchedVolumeUnit": 0,
            "LoaFormat": "26'",
            "MaxDraftFormat": "2' 6\"",
            "MinDraftFormat": "--",
            "BeamFormat": "10'",
            "AcceptsCrypto": false,
            "ShowOnCustomerSite": true
        },
        {
            "VesselID": 239441,
            "CompanyID": 899,
            "MLSID": 239441,
            "VesselStatus": 1,
            "VesselCondition": 2,
            "Year": 1992,
            "MainPhotoID": 1796064,
            "VesselType": 1,
            "ModelYear": 1992,
            "YearBuilt": 1992,
            "MainCategoryID": 2664,
            "MainCategoryText": "Cruising or Racing Sailboat",
            "StateRooms": 1,
            "TaxPaidID": 2564,
            "LOAFeet": 44.000000,
            "Length": 44.0000,
            "Beam": 13.7500,
            "MinDraft": 0.0,
            "MaxDraft": 8.2500,
            "MSRPPrice": 0.0000,
            "MSRPPriceCurrencyID": 2563,
            "Buildername": "REICHEL/PUGH",
            "BuilderID": 4522,
            "WeightUnitType": 1,
            "LOAMeters": 13.410000,
            "BeamFeet": 13.750000,
            "BeamMeters": 4.190000,
            "DraftMinFeet": 0.000000,
            "DraftMinMeters": 0.000000,
            "DraftMaxFeet": 8.250000,
            "DraftMaxMeters": 2.510000,
            "GrossTonnage": 0.0,
            "GrossTonnagePounds": 0.0,
            "GrossTonnageConverted": 0.0,
            "LengthUnit": 1,
            "WeightUnit": 1,
            "VolumeUnit": 1,
            "tags": [],
            "AskingPrice": 86000.0000,
            "AskingPriceCurrency": 2563,
            "PriceOnApplication": false,
            "IsStartingPrice": false,
            "VesselName": "SIESTA",
            "PreviousName1": "",
            "PreviousName2": "",
            "PreviousName3": "",
            "PreviousName4": "",
            "PreviousName5": "",
            "AskingPriceFormatted": "$86,000 USD",
            "AskingPriceFormattedNoCurrency": "$86,000",
            "AskingPriceCompare": 86000.000000,
            "MSRPPriceFormatted": "Price on Application",
            "MSRPPriceFormattedNoCurrency": "Price on Application",
            "BuilderName": "REICHEL/PUGH",
            "BrokerTeaser": "",
            "Country": "United States",
            "State": "California",
            "City": "San Diego",
            "RegionID": 456,
            "Region": "California - South",
            "Cruising": false,
            "LocationCountryID": 233,
            "LocationCountry": "United States",
            "LocationStateID": 1416,
            "HullMaterial": "Composite",
            "HullMaterialID": 2431,
            "HasVideo": false,
            "LocationState": "California",
            "LocationCityID": 125802,
            "LocationCity": "San Diego",
            "LocationSubRegionID": 12,
            "LocationSubRegion": "North America",
            "MainPhotoUrl": "https://s3.amazonaws.com/boss.yatco.com/ForSale/Vessel/Photo/239441/small_1796064.jpg",
            "MainPhotoMedURL": "https://s3.amazonaws.com/boss.yatco.com/ForSale/Vessel/Photo/239441/medium_1796064.jpg",
            "Model": " RP44",
            "IsModel": false,
            "SoldSecret": false,
            "ActiveDate": "2017-05-24T17:33:41.987",
            "ModifiedDate": "2017-05-26T12:26:40",
            "DaysOnMarket": 2528,
            "DaysTillExpiration": "N/A",
            "RecordAgeHours": 60609,
            "BrokerList": [
                {
                    "CompanyID": 899,
                    "OfficeID": 899,
                    "BrokerID": 22734,
                    "BrokerName": "Stephen Rock",
                    "BrokerEmail": "reichelpughbrokerage@gmail.com",
                    "BrokerPhotoUrlSmall": "https://s3-external-1.amazonaws.com/common.yatcoboss.com/PhotoDefault/Account/default.jpg",
                    "CompanyName": "Reichel-Pugh Yacht Brokerage",
                    "CompanyAddress1": "2726 Shelter Island Dr #535",
                    "CompanyAddress2": "",
                    "CompanyCity": "San Diego",
                    "CompanyState": "California",
                    "CompanyZip": "92106",
                    "CompanyCountry": "United States",
                    "CompanyPhotoUrl": "https://s3-external-1.amazonaws.com/common.yatcoboss.com/PhotoDefault/Company/yatcoboss_nologo.jpg",
                    "VesselID": 239441
                }
            ],
            "AssistantList": [],
            "DataSource": 1,
            "Open": false,
            "AgreementTypeID": 2546,
            "SearchedLengthUnit": 1,
            "SearchedCurrency": 0,
            "SearchedVolumeUnit": 0,
            "LoaFormat": "44'",
            "MaxDraftFormat": "8' 3\"",
            "MinDraftFormat": "--",
            "BeamFormat": "13' 9\"",
            "AcceptsCrypto": false,
            "ShowOnCustomerSite": true
        },
        {
            "VesselID": 303665,
            "CompanyID": 1220,
            "MLSID": 275520,
            "VesselStatus": 1,
            "VesselCondition": 2,
            "Year": 1978,
            "MainPhotoID": 3413834,
            "VesselType": 1,
            "ModelYear": 1978,
            "YearBuilt": 1978,
            "MainCategoryID": 2662,
            "MainCategoryText": "Cruising Ketch",
            "StateRooms": 2,
            "LOAFeet": 41.000000,
            "Length": 41.0000,
            "Beam": 0.0,
            "MinDraft": 0.0,
            "MaxDraft": 0.0,
            "MSRPPrice": 0.0000,
            "MSRPPriceCurrencyID": 2563,
            "Buildername": "",
            "BuilderID": 6909,
            "WeightUnitType": 4,
            "LOAMeters": 12.490000,
            "BeamFeet": 0.000000,
            "BeamMeters": 0.000000,
            "DraftMinFeet": 0.000000,
            "DraftMinMeters": 0.000000,
            "DraftMaxFeet": 0.000000,
            "DraftMaxMeters": 0.000000,
            "GrossTonnage": 0.0,
            "GrossTonnagePounds": 0.0,
            "GrossTonnageConverted": 0.0,
            "LengthUnit": 1,
            "WeightUnit": 4,
            "VolumeUnit": 1,
            "tags": [],
            "AskingPrice": 62500.0000,
            "AskingPriceCurrency": 2563,
            "PriceOnApplication": false,
            "IsStartingPrice": false,
            "VesselName": "ETHEREAL",
            "AskingPriceFormatted": "$62,500 USD",
            "AskingPriceFormattedNoCurrency": "$62,500",
            "AskingPriceCompare": 62500.000000,
            "MSRPPriceFormatted": "Price on Application",
            "MSRPPriceFormattedNoCurrency": "Price on Application",
            "BuilderName": "",
            "BrokerTeaser": "",
            "Country": "United States",
            "State": "California",
            "City": "Napa",
            "RegionID": 455,
            "Region": "California - North",
            "LocationCountryID": 233,
            "LocationCountry": "United States",
            "LocationStateID": 1416,
            "HullMaterial": "Fiberglass",
            "HullMaterialID": 2434,
            "HasVideo": false,
            "LocationState": "California",
            "LocationCityID": 122546,
            "LocationCity": "Napa",
            "LocationSubRegionID": 12,
            "LocationSubRegion": "North America",
            "MainPhotoUrl": "https://s3.amazonaws.com/boss.yatco.com/ForSale/Vessel/Photo/303665/small_3413834.jpg",
            "MainPhotoMedURL": "https://s3.amazonaws.com/boss.yatco.com/ForSale/Vessel/Photo/303665/medium_3413834.jpg",
            "IsModel": false,
            "SoldDate": "2022-01-10T19:00:00",
            "SoldSecret": false,
            "ActiveDate": "2022-01-11T14:06:53.827",
            "ModifiedDate": "2022-01-11T14:06:53.85",
            "DaysOnMarket": 835,
            "DaysTillExpiration": "N/A",
            "RecordAgeHours": 20022,
            "BrokerList": [
                {
                    "CompanyID": 1220,
                    "OfficeID": 1277,
                    "BrokerID": 26888,
                    "BrokerName": "Kirby Long",
                    "BrokerPhone": "(707) 252-8011",
                    "BrokerEmail": "nvmkirby@yahoo.com",
                    "BrokerMobile": "707-732-6101",
                    "BrokerPhotoUrlSmall": "https://s3-external-1.amazonaws.com/common.yatcoboss.com/PhotoDefault/Account/default.jpg",
                    "CompanyName": "Napa Valley Marina",
                    "CompanyAddress1": "1200 Milton Rd",
                    "CompanyCity": "Napa",
                    "CompanyState": "California",
                    "CompanyZip": "94559",
                    "CompanyCountry": "United States",
                    "CompanyPhotoUrl": "https://s3-external-1.amazonaws.com/boss.yatco.com/CMS/Company/Photo/small_2297.jpg",
                    "VesselID": 303665
                }
            ],
            "AssistantList": [],
            "DataSource": 1,
            "Open": false,
            "AgreementTypeID": 2546,
            "SearchedLengthUnit": 1,
            "SearchedCurrency": 0,
            "SearchedVolumeUnit": 0,
            "LoaFormat": "41'",
            "MaxDraftFormat": "--",
            "MinDraftFormat": "--",
            "BeamFormat": "--",
            "AcceptsCrypto": false,
            "ShowOnCustomerSite": true
        },
        {
            "VesselID": 303695,
            "CompanyID": 1220,
            "MLSID": 275550,
            "VesselStatus": 1,
            "VesselCondition": 2,
            "Year": 1971,
            "MainPhotoID": 3414713,
            "VesselType": 1,
            "ModelYear": 1971,
            "YearBuilt": 1971,
            "MainCategoryID": 3480,
            "MainCategoryText": "Yawl",
            "StateRooms": 2,
            "LOAFeet": 40.000000,
            "Length": 40.0000,
            "Beam": 10.7500,
            "MinDraft": 0.0,
            "MaxDraft": 6.9166,
            "MSRPPrice": 0.0000,
            "MSRPPriceCurrencyID": 2563,
            "Buildername": "CHEOY LEE",
            "BuilderID": 497,
            "WeightUnitType": 4,
            "LOAMeters": 12.190000,
            "BeamFeet": 10.750000,
            "BeamMeters": 3.270000,
            "DraftMinFeet": 0.000000,
            "DraftMinMeters": 0.000000,
            "DraftMaxFeet": 6.910000,
            "DraftMaxMeters": 2.100000,
            "GrossTonnage": 0.0,
            "GrossTonnagePounds": 0.0,
            "GrossTonnageConverted": 0.0,
            "LengthUnit": 1,
            "WeightUnit": 4,
            "VolumeUnit": 1,
            "tags": [],
            "AskingPrice": 38500.0000,
            "AskingPriceCurrency": 2563,
            "PriceOnApplication": false,
            "IsStartingPrice": false,
            "VesselName": "MARY T",
            "AskingPriceFormatted": "$38,500 USD",
            "AskingPriceFormattedNoCurrency": "$38,500",
            "AskingPriceCompare": 38500.000000,
            "MSRPPriceFormatted": "Price on Application",
            "MSRPPriceFormattedNoCurrency": "Price on Application",
            "BuilderName": "CHEOY LEE",
            "BrokerTeaser": "",
            "Country": "United States",
            "State": "California",
            "City": "Napa",
            "RegionID": 455,
            "Region": "California - North",
            "LocationCountryID": 233,
            "LocationCountry": "United States",
            "LocationStateID": 1416,
            "HullMaterial": "Fiberglass",
            "HullMaterialID": 2434,
            "HasVideo": false,
            "LocationState": "California",
            "LocationCityID": 122546,
            "LocationCity": "Napa",
            "LocationSubRegionID": 12,
            "LocationSubRegion": "North America",
            "MainPhotoUrl": "https://s3.amazonaws.com/boss.yatco.com/ForSale/Vessel/Photo/303695/small_3414713.jpg",
            "MainPhotoMedURL": "https://s3.amazonaws.com/boss.yatco.com/ForSale/Vessel/Photo/303695/medium_3414713.jpg",
            "IsModel": false,
            "SoldDate": "2022-01-11T19:00:00",
            "SoldSecret": false,
            "ActiveDate": "2022-01-12T14:42:12.027",
            "ModifiedDate": "2022-01-12T14:42:12.097",
            "DaysOnMarket": 834,
            "DaysTillExpiration": "N/A",
            "RecordAgeHours": 19998,
            "BrokerList": [
                {
                    "CompanyID": 1220,
                    "OfficeID": 1277,
                    "BrokerID": 26888,
                    "BrokerName": "Kirby Long",
                    "BrokerPhone": "(707) 252-8011",
                    "BrokerEmail": "nvmkirby@yahoo.com",
                    "BrokerMobile": "707-732-6101",
                    "BrokerPhotoUrlSmall": "https://s3-external-1.amazonaws.com/common.yatcoboss.com/PhotoDefault/Account/default.jpg",
                    "CompanyName": "Napa Valley Marina",
                    "CompanyAddress1": "1200 Milton Rd",
                    "CompanyCity": "Napa",
                    "CompanyState": "California",
                    "CompanyZip": "94559",
                    "CompanyCountry": "United States",
                    "CompanyPhotoUrl": "https://s3-external-1.amazonaws.com/boss.yatco.com/CMS/Company/Photo/small_2297.jpg",
                    "VesselID": 303695
                }
            ],
            "AssistantList": [],
            "DataSource": 1,
            "Open": false,
            "AgreementTypeID": 2546,
            "SearchedLengthUnit": 1,
            "SearchedCurrency": 0,
            "SearchedVolumeUnit": 0,
            "LoaFormat": "40'",
            "MaxDraftFormat": "6' 11\"",
            "MinDraftFormat": "--",
            "BeamFormat": "10' 9\"",
            "AcceptsCrypto": false,
            "ShowOnCustomerSite": true
        }
    ],
    "Count": 10,
    "Records": 12,
    "Offset": 0
}
