var vessel_296425 = {
  Accomodation: {
    VesselID: 296425,
    StateRooms: 3,
    NumSleeps: 8,
    NumHeads: 1,
    CaptainQuarters: false,
    CaptainOnBoard: false,
  },
  Description: {
    VesselID: 296425,
    CultureID: 1,
    VesselDescriptionShowingInstructions: "",
    VesselDescriptionBrokerTeaser:
      "Used Geminis generally offer excellent value, outstanding accommodations, and solid sailing performance. Seller's bought the vessel new and have continued to keep the vessel in pristine condition. Currently dry docked for your viewing.",
    VesselDescriptionShortDescription: "",
    VesselDescriptionShortDescriptionStripped: "",
    VesselDescriptionShortDescriptionNoStyles: "",
    VesselDescriptionInternalTeaser: "",
    VesselName: "Andimo",
    Loading_ShortDescription: false,
    Loading_MyWebSiteDescription: false,
    Loading_YatcoDotComDescription: false,
  },
  SearchEngineOptimization: {
    VesselID: 0,
  },
  Dimension: {
    VesselID: 296425,
    LengthUnitType: 1,
    Length: 33.5,
    Beam: 14.0,
    MinDraft: 1.5,
    MaxDraft: 5.5,
    WeightUnitType: 1,
    Weight: 9600.0,
    SpeedUnitType: 1,
    VolumeUnitType: 1,
    FuelCapacity: 36.0,
    WaterCapacity: 30.0,
    HoldingTank: 18.0,
  },
  Engines: [
    {
      EngineID: 256850,
      VesselID: 296425,
      ManufacturerID: 3010,
      EngineNumber: 1,
    },
    {
      EngineID: 256851,
      VesselID: 296425,
      ManufacturerID: 2907,
      EngineTypeID: 2541,
      HorsePower: 27,
      Hours: 900,
      EngineNumber: 2,
    },
  ],
  HullDeck: {
    VesselID: 296425,
    HullID: "PC1009231506",
    HullMaterialID: 2434,
    HullFinishID: 2481,
    HullTypeId: 1,
    DeckMaterialID: 2463,
    SuperstructureMaterialID: 3476,
  },
  Info: {
    VesselID: 296425,
    BoatName: "Andimo",
    VesselType: 1,
    VesselCondition: 2,
    VesselStatus: 4,
    BuilderID: 981,
    YearBuilt: 2006,
    Model: "105Mc",
    ModelYear: 2006,
    TopID: 2363,
    FlyBridge: false,
    Cockpit: true,
    Helipad: false,
    MainCategoryID: 2384,
    SubCategoryID: 3232,
    RigID: 1,
    SailCockpitID: 2657,
    MainPhotoID: 3098340,
    ActiveDate: "2020-11-13T00:45:12.593",
    ModifyDate: "2021-03-16T14:35:33.177",
    Deleted: false,
    ShowOnPro: true,
    ShowOnConsumer: true,
    ShowOnCompanySite: true,
    ShowOnOtherCompaniesSites: true,
    Concept: false,
    Commercial: false,
    ForCharter: false,
    Elevator: false,
    HandicapAccessible: false,
    MLSID: 268374,
    ProductionTypeId: 0,
    LeadTime: 0,
    isComingFromBoatShowVessel: false,
    VesselRating: 1,
    IsVesLengthGreaterThanEightyFeet: false,
  },
  Listing: {
    CompanyID: 1220,
    VesselID: 296425,
    SoldDate: "2020-11-11T23:59:00",
    SoldBrokerID: 26888,
    AskingPrice: 114900.0,
    PriceOnApplication: false,
    IsStartingPrice: false,
    CurrencyID: 2563,
    Fractional: false,
    AgreementTypeID: 2546,
    OfficeID: 1277,
    BrokerID: 26888,
    AvailableCoBroker: 1,
    SoldSecret: false,
    Flag: "United States",
    NotForSaleInUS: false,
    ListingBrokerPercentage: 100,
    NewToMarket: false,
    PriceChange: false,
    VesselStatus: 4,
    HullID: "PC1009231506",
  },
  Location: {
    VesselID: 296425,
    StateID: 313,
    CountryID: 119,
    RegionID: 455,
    City: "Napa",
    ZipCode: "94559",
    LocationStateID: 1416,
    LocationCountryID: 233,
    LocationCityID: 122546,
    LocationCity: "Napa",
    LocationCountry: "United States",
    LocationState: "California",
  },
  Brokers: [
    {
      RecID: 161520,
      VesselID: 296425,
      BrokerID: 26888,
      FirstName: "Kirby",
      LastName: "Long",
      Phone: "(707) 252-8011",
      Mobile: "707-732-6101",
      Fax: "707-252-0851",
      CompanyLogoURL:
        "https://s3.amazonaws.com/boss.yatco.com/CMS/Company/Photo/medium_2297.jpg",
      PhotoURL:
        "https://s3.amazonaws.com/common.yatcoboss.com/PhotoDefault/Account/default.jpg",
      Email: "nvmkirby@yahoo.com",
      OfficeID: 1277,
      ExternalBroker: false,
      toString: "Kirby Long: nvmkirby@yahoo.com ((707) 252-8011)",
    },
  ],
  ProjectInfo: {
    BuilderModuleID: 0,
    LeadTime: 0,
  },
};
